(add-to-list 'load-path "~/.emacs.d/config")

;; conf-* = Package Configurations
(load "conf-ido")
(load "conf-dired")
(load "conf-recentf")
(load "conf-org")
;; (load "config/flymake-conf")
;; (load "config/javascript-conf")
;; (load "config/ri-emacs-conf")
(load "conf-evil")
(load "conf-color-theme")
;; (load "config/hl-line-conf")
(load "conf-server-mode")
(load "conf-tabbar")
;; (load "config/shell-mode")
