(add-to-list 'load-path "~/.emacs.d/cmn-prefs")
(require 'defuns)

;; pref-* = Personal Preferences
(try-error (load "pref-env"))
(try-error (load "pref-global"))
(try-error (load "pref-flymake"))
(try-error (load "pref-bindings"))
(try-error (load "pref-screen"))
(try-error (load "pref-tabs"))
(try-error (load "pref-disabled"))
(try-error (load "pref-hl-line"))
(try-error (load "pref-fonts"))
(try-error (load "pref-utf-8"))
(try-error (load "pref-scratch"))
(try-error (load "pref-rectangle"))
(try-error (load "pref-zoom"))
(try-error (load "pref-grep"))
(try-error (load "pref-diff"))
(try-error (load "pref-mac"))

