(add-to-list 'load-path "~/.emacs.d/cmn-prefs")

;; pref-* = Personal Preferences
(load "pref-env")
(load "pref-global")
(load "pref-flymake")
(load "pref-bindings")
(load "pref-screen")
(load "pref-tabs")
(load "pref-disabled")
(load "pref-hl-line")
(load "pref-fonts")
(load "pref-utf-8")
(load "pref-scratch")
(load "pref-rectangle")
(load "pref-zoom")
(load "pref-grep")
(load "pref-diff")
(load "pref-mac")

