(add-to-list 'load-path "~/.emacs.d/package-configs")

;; conf-* = Package Configurations
(load "conf-ido")
(load "conf-dired")
(load "conf-recentf")
(load "conf-org")
(load "conf-evil")
(load "conf-color-theme")
(load "conf-server-mode")
(load "conf-tabbar")
(load "conf-yasnippet")
(load "conf-auto-complete")
(load "conf-python-mode")
;; (load "config/shell-mode")
