(add-to-list 'load-path "~/.emacs.d/config")

(load "env-conf")
(load "global-conf")
(load "bindings-conf")
(load "screen-conf")
(load "tabs-conf")
(load "disabled-conf")
(load "fonts-conf")
(load "utf-8-conf")
(load "scratch-conf")
(load "grep-conf")
(load "diff-conf")
(load "ido-conf")
(load "dired-conf")
(load "recentf-conf")
(load "rectangle-conf")
(load "org-conf")
(load "zoom-conf")
;; (load "config/flymake-conf")
;; (load "config/javascript-conf")
;; (load "config/ri-emacs-conf")
(load "mac-conf")
(load "evil-conf")
(load "conf-color-theme")
;; (load "config/hl-line-conf")
(load "config/server-mode-conf")
;; (load "config/shell-mode")
