(add-to-list 'load-path "~/.emacs.d/config")

(load "config/env-conf")
(load "config/global-conf")
(load "config/bindings-conf")
(load "config/screen-conf")
(load "config/tabs-conf")
(load "config/disabled-conf")
(load "config/fonts-conf")
(load "config/utf-8-conf")
(load "config/scratch-conf")
(load "config/grep-conf")
(load "config/diff-conf")
(load "config/ido-conf")
(load "config/dired-conf")
(load "config/recentf-conf")
(load "config/rectangle-conf")
(load "config/org-conf")
(load "config/zoom-conf")
;; (load "config/flymake-conf")
;; (load "config/javascript-conf")
;; (load "config/ri-emacs-conf")
(load "config/mac-conf")
;; (load "config/hl-line-conf")
;; (load "config/server-mode-conf")
;; (load "config/shell-mode")

